DROP TABLE IF EXISTS Attendance_Log;
DROP TABLE IF EXISTS Leave_Requests;
DROP TABLE IF EXISTS Contract;
DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Position;
DROP TABLE IF EXISTS EntityDepartment;
